# Generated by Django 4.2.2 on 2023-08-09 21:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[core.validators.validate_name]),
        ),
    ]
