# Generated by Django 4.2.2 on 2023-08-15 15:23

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, validators=[core.validators.validate_encoded_field, core.validators.validate_non_empty])),
                ('priority', models.CharField(choices=[('h', 'High'), ('m', 'Medium'), ('l', 'Low'), ('n', 'None')], default='n', max_length=1)),
                ('failed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('date_closed', models.DateField(blank=True, default=None, null=True, validators=[core.validators.validate_date_past_or_present])),
                ('note', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.note')),
                ('parent_task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task')),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.todolist')),
            ],
        ),
    ]
